### PR TITLE
table suggestion for api

### PR DESCRIPTION
**Pull request by i-walker**
I will add the sql file with the updated data in the 2. commit.

### CODE REVIEW

**Comment by kordianbruck** [comment]
Perfect, this worked. Here is one schema:
@jacqueline8711 this might be useful for you locally.

```
CREATE TABLE IF NOT EXISTS `openinghours` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(140) COLLATE utf8mb4_unicode_ci NOT NULL,
  `room` varchar(140) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transport_station` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `opening_hours` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `infos` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table openinghours: ~56 rows (approximately)
/*!40000 ALTER TABLE `openinghours` DISABLE KEYS */;
INSERT INTO `openinghours` (`id`, `category`, `name`, `address`, `room`, `transport_station`, `opening_hours`, `infos`, `url`) VALUES
	(1, 'library', 'Stammgelände', 'Arcisstr. 21, 80333 München', '1.OG', 'U2 Königsplatz/Theresienstraße', 'Mo-Fr 8-24, Sa-So 9-22', '☎️ 089-189-659-220/nWhatsApp 0173-861-8412/n📩 information@ub.tum.de', 'https://www.ub.tum.de/en/branch-library-main-campus'),
	(2, 'library', 'LRZ-Stützpunkt Stammgelände', 'Arcisstr. 21, 80333 München', '1.OG Raum 1163', 'U2 Königsplatz/Theresienstraße', 'Mo-Do 8-16, Fr 8-14', '☎️ 089-189-659-220/n📩 information@ub.tum.de', 'https://www.ub.tum.de/oeffnungszeiten/LRZ-Stützpunkt'),
	(3, 'library', 'Medizin', 'Nigerstr. 3, 81675 München', '', 'U4 Prinzregentenplatz, Tram 19 Flurstraße', 'Abholen vorbestellter Bücher: Mo-Fr 9-20', '📩 information@ub.tum.de/nLesesaal bis 15.04.2019 wg. Umbau geschlossen', 'https://www.ub.tum.de/oeffnungszeiten/Medizin'),
	(4, 'library', 'Sportwissenschaft', 'Georg-Brauchle-Ring 62, 80992 München', '1.OG', 'U1 Georg-Brauchle-Ring', 'Bis 07.04.2019:/nMo-Do 9-16, Fr 9-14', '☎️ 089-289-24601/n📩 information@ub.tum.de', 'https://www.ub.tum.de/en/branch-library-sport-health-sciences'),
	(5, 'library', 'Life Sciences (Weihenstephan)', 'Maximus-von-Imhof-Forum 1-3, 85354 Freising', '', 'Bus 614/615/637-640/6002 Weihenstephan, Freising', 'Mo-Fr 8-24, Sa-So 10-20', '☎️ 08161-713240/n📩 information@ub.tum.de', 'https://www.ub.tum.de/en/branch-library-life-sciences'),
	(6, 'library', 'Chemie', 'Lichtenbergstr. 4, 85748 Garching', 'EG', '', 'Mo-Do 8-21, Fr 8-19', '☎️ 089-189-659-220/n📩 information@ub.tum.de', 'https://www.ub.tum.de/en/branch-library-mechanical-engineering'),
	(7, 'library', 'Maschinenwesen', 'Boltzmannstr. 15, 85748 Garching', '1. OG', '', 'Mo-Do 8-21, Fr 8-19', '☎️ 089-189-659-220/n📩 information@ub.tum.de', 'https://www.ub.tum.de/oeffnungszeiten'),
	(8, 'library', 'Mathematik', 'Boltzmannstr. 3, 85748 Garching', 'EG', '', 'Mo-Fr 9-24, Sa, So, Feiertag 10-20', '☎️ 089-189-659-220/n📩 information@ub.tum.de', 'https://www.ub.tum.de/teilbibliothek-mathematik-informatik'),
	(9, 'library', 'Physik', 'James-Franck-Str., 85748 Garching', '1. OG', '', 'Mo-Fr 9-21', '☎️ 089-189-659-220/n📩 information@ub.tum.de', 'https://www.ub.tum.de/teilbibliothek-physik'),
	(10, 'cafeteria_gar', 'Mensa Garching', 'Lichtenbergstr. 2, 85748 Garching', '', '', 'Mo-Do 11-16, Fr 11-13:45/nvorl.frei Zeit: Mo-Do bis 14/nFr 11-13:45', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/garching/#c1430'),
	(11, 'cafeteria_gar', 'Mensa Garching Infopoint', 'Lichtenbergstr. 2, 85748 Garching', '', '', 'Mo-Fr 11-14/nvorl.frei Zeit: bis 13:30', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/garching/#c1433'),
	(12, 'cafeteria_gar', 'StuCafé Mensa Garching', 'Lichtenbergstr. 2, 85748 Garching', '', '', 'Mo-Do 8:30-15:45, Fr 8:30-14:15/nvorl.frei Zeit: Mo-Do bis 15:15/nFr 8:30-14:15', 'Bezahlart: Legic-Karte oder Bar', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/garching/#c1432'),
	(13, 'cafeteria_gar', 'StuCafé Boltzmannstraße', 'Boltzmannstr. 15, 85748 Garching', '', '', 'Mo-Do 8-18, Fr 8-17/nvorl.frei Zeit: Mo-Do bis 15:15/nFr bis 14:30', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/garching/#c1434'),
	(14, 'cafeteria_gar', 'Espresso-Bar & Kiosk Maschinenwesen', 'Boltzmannstr. 15, 85748 Garching', '', '', 'Mo-Do 7-19, Fr 7-17/nvorl.frei Zeit: Mo-Do bis 17/nFr bis 15', 'Bezahlart: Legic-Karte oder Bar', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/garching/#c1435'),
	(15, 'cafeteria_gar', 'C2 Campus-Cneipe', 'Lichtenbergstr. 2, 85748 Garching', '', '', 'Di-Do 16-23', 'Reservierung: 08930785757 oder Online', 'https://www.c2.tum.de/kontakt-reservierung/'),
	(16, 'cafeteria', 'Mensa Leopoldstraße', 'Leopoldstr. 13a, 80802 München', '', 'U3/U6 Giselastraße', 'Mo-Do 11-16, Fr 11-14/nvorl.frei Zeit: Mo-Fr bis 14', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c15346'),
	(17, 'cafeteria', 'Mensa Arcisstraße', 'Arcisstr. 17, 80333 München', '', 'Bus 58/100 Technische Universität/nU2/U8 Königsplatz oder Theresienstraße', 'Mo-Do 11-16, Fr 11-14/nvorl.frei Zeit: Mo-Do bis 14, Fr bis 13:45', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1453'),
	(18, 'cafeteria', 'Mensa Lothstraße', 'Lothstr. 13d, 80335 München', '', 'Tram 20/21/22/N20 Hochschule München (Lothstraße)', 'Mo-Do 08:30-15:30, Fr 08:30-15:00/nvorl.frei Zeit: Mo-Fr 09-15', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1457'),
	(19, 'cafeteria', 'StuCafé Karlstraße', 'Karlstr. 6, 80333 München', '', 'Tram 10/27/28/N27 Ottostraße', 'Mo-Do 8.15-15:00, Fr bis 14:30/nAusgabezeiten: Mo-Do 11-14/nvorl.frei Zeit: Mo-Fr 9-14', 'Geschlossen: von 14.02. bis 17.03.19/nBezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1459'),
	(20, 'cafeteria', 'StuCafé Audimax', 'Arcisstr. 21, 80333 München', '', 'Bus 58/100 Technische Universität', 'Mo-Do 7:30-19:00, Fr 7:30-18:00/nSa 10:30-14:30/nvorl.frei Zeit: Mo-Do 7:30-15:30/nFr 7:30-14:30', 'Bezahlart: Legic-Karte oder Bar', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1454'),
	(21, 'cafeteria', 'StuCafé Adalbertstraße', 'Adalbertstr. 5, 80799 München', '', 'U6 Universität', 'Mo-Do 9-17, Fr 9:00-16:30/nvorl.frei Zeit: Mo-Do 9-15, Fr 9:00-14:30', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1451'),
	(22, 'cafeteria', 'StuCafé Heßstraße', 'Lothstr. 64, 80335 München', '', 'Bus 153 oder Tram 20/21/22/N20 Hochschule München (Lothstr.)', 'Mo-Do 08:30-15:30, Fr 08:30-15:00/nvorl.frei Zeit: Mo-Fr 09-15', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1458'),
	(23, 'cafeteria', 'StuCafé in der Mensa Leopoldstraße', 'Leopoldstr. 13a, 80802 München', '', 'U3/U6 Giselastraße', 'Mo-Do 08:00-16:30, Fr 08-15/nvorl.frei Zeit: Mo-Do 9-15, Fr 09:00-14:30', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c15346'),
	(24, 'cafeteria', 'Crazy Bean Bar', 'Arcisstr. 17, 80333 München', '', 'Bus 58/100 Technische Universität/nU2/U8 Königsplatz oder Theresienstraße', 'Mo-Fr 8-17/nvorl.frei Zeit: Mo-Do bis 16, Fr bis 15', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c322'),
	(25, 'cafeteria', 'Espresso-Bar in der Mensa Leopoldstraße', 'Leopoldstr. 13a, 80802 München', '', 'U3/U6 Giselastraße', 'Mo-Do 9:00-16.30, Fr 9:00-15.30/nvorl.frei Zeit: Mo-Do bis 15:30, Fr bis 15:00', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c3098'),
	(26, 'cafeteria', 'Espresso-Bar im Jurist. Seminargeb.', 'Ludwigstr. 28, 80539 München', '', 'U3/U6 Universität', 'Mo-Fr 9-18', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1450'),
	(27, 'cafeteria', 'StuCafé Olympiapark', 'Connollystr. 32, 80809 München', '', 'U3/U8 Olympiazentrum', 'Mo-Fr 10-14/nvorl.frei Zeit: Mo-Fr 11-14', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1455'),
	(28, 'cafeteria', 'StuBistro Schellingstraße', 'Schellingstr. 3, 80799 München', '', 'Bus 153/154 Universität', 'Mo-Do 09:00-16:30, Fr 9:00-14.30/nAusgabezeiten: Mo-Fr 11-14/nvorl.frei Zeit: Mo-Do 10-15, Fr 10:00-14:30', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1449'),
	(29, 'cafeteria', 'StuBistro Schillerstraße', 'Schillerstr. 47, 80336 München', '', 'U1/U2/U3/U6/U7/U8 Sendlinger Tor/nU1/U2/U4/U5/U7/U8 Hauptbahnhof', 'Mo-Fr 09:00-14:30/nAusgabezeiten: Mo-Fr 11-14,', 'Geschlossen: von 11.02. bis 22.04.19/nBezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1448'),
	(30, 'cafeteria', 'StuBistro Goethestraße', 'Goethestr. 70, 80336 München', '', 'U3/U6 Goetheplatz', 'Mo-Fr 09:00-14:30/nAusgabezeiten: Mo-Do 11-14, Fr bis 13:30/nvorl.frei Zeit: Mo-Do 10-14', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/#c1447'),
	(31, 'cafeteria_pas', 'Mensa Pasing', 'Am Stadtpark 20, 81243 München', '', 'Bus 160 Avenariusplatz', 'Mo-Do 11-14, Fr 11-13.30', 'Geschlossen: von 11.02. bis 17.03.19/nBezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/pasing/'),
	(32, 'cafeteria_pas', 'StuCafé Pasing', 'Am Stadtpark 20, 81243 München', '', 'Bus 160 Avenariusplatz', 'Mo-Do 8-15, Fr 8-14.30/nvorl.frei Zeit:/nMo-Do 9-10 & 10:30-14:30/nFr 9-10 & 10:30-13:30', 'Geschlossen: von 04.03. bis 05.03.19/nBezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/pasing/'),
	(33, 'cafeteria_wst', 'Mensa Weihenstephan', 'Maximus-von-Imhof-Forum 5/n85354 Freising', '', 'Bus 614/615/637-640/6002 Weihenstephan, Freising', 'Mo-Fr 11-13.30/nInfopoint:Mo-Fr 11-14', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/freising-weihenstephan/#c1439'),
	(34, 'cafeteria_wst', 'StuCafé in der Mensa Weihenstephan', 'Maximus-von-Imhof-Forum 5/n85354 Freising', '', 'Bus 614/615/637-640/6002 Weihenstephan, Freising', 'Mo-Do 8:30-16.00, Fr 8:30-14:30/nvorl.frei Zeit: Mo-Do bis 16/nFr bis 14:30', 'Bezahlart: Legic-Karte oder Bar', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/freising-weihenstephan/#c1440'),
	(35, 'cafeteria_wst', 'StuCafé Akademie', 'Altes Akademiegebäude/n85354 Freising', '', '', 'Mo-Do 11-14, Fr 11-13.15', '@Google/nThis seems to be permanently closed', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/freising-weihenstephan/#c1442'),
	(36, 'cafeteria_wst', 'Espresso-Bar Mensa Weihenstephan', 'Maximus-von-Imhof-Forum 5/n85354 Freising', '', 'Bus 614/615/637-640/6002 Weihenstephan, Freising', 'Mo-Fr 10.30-14.30', 'Bezahlart: Bar', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/freising-weihenstephan/#c1441'),
	(37, 'cafeteria_grh', 'Mensa Martinsried', 'Großhaderner Str. 6/n82152 Planegg-Martinsried', '', '', 'Mo-Do 11-14, Fr 11-13.30', '', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/martinsried-grosshadern/#c1471'),
	(38, 'cafeteria_grh', 'StuBistro Großhadern', 'Butenandtstr. 13, Gebäude F/n81375 München', '', '', 'Mo-Do 8:00-15:15, Fr 8:00-14:15', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/martinsried-grosshadern/#c5871'),
	(39, 'cafeteria_grh', 'StuBistro Martinsried', 'Großhadernerstr. 9a/n82152 Planegg-Martinsried', '', 'Bus 259 LMU Martinsried, Martinsried', 'Mo-Do 8-17, Fr bis 15/nEssensausgabe:/nMo-Do 11-15 Fr bis 14:30/nvorl.frei Zeit: Mo-Fr 9-15/nEssensausgabe in vorlfreiZeit:/n Mo-Fr 11:00-14:30', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/martinsried-grosshadern/'),
	(40, 'cafeteria_grh', 'StuLounge BioSys', 'Butenandtstr. 15, 81377 München', '', 'Bus 160/268 Waldhüterstraße', 'Mo-Fr 10:00-14:30, Fr 8:00-14:15', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/martinsried-grosshadern/'),
	(41, 'cafeteria_grh', 'Espresso-Bar Biozentrum Martinsried', 'Großhaderner Str. 2/n82152 Planegg-Martinsried', '', 'Bus 259 LMU Martinsried, Martinsried', 'Mo-Do 8-15 & Fr 8:00-14:30/nvorl.frei Zeit: Mo-Fr 8:00-14:30', 'Bezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/martinsried-grosshadern/'),
	(42, 'cafeteria_grh', 'StuLounge im BMC Martinsried', 'Großhaderner Str. 9/n82152 Planegg-Martinsried', '', 'Bus 259 LMU Martinsried, Martinsried', 'Mo/Di/Do 8-10 & 10:30-15:00/nMi/Fr 8-10 & 10:30-14:30', 'Geschlossen: von 11.02. bis 22.04.19/nBezahlart: Legic-Karte', 'https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/martinsried-grosshadern/'),
	(43, 'info', 'Skriptenverkauf Fachschaft MPI', 'Boltzmannstr. 3, 85748 Garching', 'MI 00.06.039', 'U6 Garching Forschungszentrum', 'Opening hours: check the website', 'We are happy to help: skripten@fs.tum.de/nOnline catalogue: skripten.mpi.fs.tum.de/katalog/', 'https://mpi.fs.tum.de/fuer-studierende/service-der-fachschaft/skriptenverkauf/'),
	(44, 'info', 'Infopoint Informatics', 'Boltzmannstr. 3, 85748 Garching', 'MI 00.10.013', 'U6 Garching Forschungszentrum', 'Opening hours: check the website', '☎️  089-289-17593/nSubmit thesis:/n15th of March, Fr 10-15', 'https://www.in.tum.de/en/current-students/services-facilities-it/infopoint/'),
	(45, 'info', 'SSZ Studierenden Service Zentrum (Beratungszentrum)', 'Arcisstraße 21, 80333 München', 'EG Service Desk, Raum 0140', 'U2 Königsplatz/Theresienstraße', 'Service Desk:/nMo-Do 9-12 & 13-16/nFr 9-12', '☎️ 089-289-22245/n📩 studium@tum.de', 'https://www.tum.de/studium/studenten-service-zentrum/'),
	(46, 'info', 'SSZ Bewerbung & Immatrikulation', 'Arcisstr. 21, 80333 München', 'EG Service Desk, Raum 0140', 'U2 Königsplatz/Theresienstraße', 'Mo-Do 9-12 & 13-16/nFr 9-12', 'Ansprechpartner: https://bit.ly/2HrGJEU /n📞089-289-22245/n📩 studium@tum.de', 'https://www.tum.de/studium/studenten-service-zentrum/'),
	(47, 'info', 'SSZ Beiträge & Stipendien', 'Arcisstr. 21, 80333 München', 'EG Räume 0157, 0159, 0161', 'U2 Königsplatz/Theresienstraße', 'Mo-Fr 9-12, Mo-Do 13-16', 'Ansprechpartner: https://bit.ly/2SXg9WC/n☎️ 089-289-22245/n📩 beitragsmanagement@zv.tum.de', 'https://www.tum.de/studium/studenten-service-zentrum/'),
	(48, 'info', 'SSZ Zentrale Prüfungs­angelegenheiten', 'Arcisstr. 21, 80333 München', 'EG Räume 0163 - 0169', 'U2 Königsplatz/Theresienstraße', 'Mo/Di/Do Fr 8:30–12:00', 'Ansprechpartnerin: Frau Fischer/n☎️ 089-289-22066/n📩 fischerv@tum.de/nVisit the website for more', 'https://www.tum.de/studium/studenten-service-zentrum/'),
	(49, 'info', 'ZHS Zentraler Hochschulsport', 'Connollystraße 32, 80809 München', '', 'U3 Olympiazentrum', 'Opening hours: https://bit.ly/2UvSNc6', 'ID payment & issuing: https://bit.ly/2TGcDnH/n☎️ 089.289.24668/n📩 zhs-h@zv.tum.de/n', 'https://www.zhs-muenchen.de/en/home/'),
	(50, 'info', 'Studienberatung Informatik (Leitung V. Simic)', 'Boltzmannstr. 3, 85748 Garching', 'MI 01.08.039', 'U6 Garching Forschungszentrum', 'Di 13:00-14:30/nDo 9:00-10:30, Fr 9-11', '☎️ 089-289-17296/n📩 studienberatung@in.tum.de/nPlease, check the website for current changes', 'https://www.in.tum.de/de/visitenkarten/simic-vivija/simic-vivija-sprechstunden/'),
	(51, 'info', 'Studienberatung Informatik', 'Boltzmannstr. 3, 85748 Garching', '', 'U6 Garching Forschungszentrum', '', '📩 studienberatung@in.tum.de', 'http://www.in.tum.de/fuer-studierende/beratung-und-unterstuetzung/studienberatung.html'),
	(52, 'info', 'Studienberatung Informatik (S. Roden-Kinghorst)', 'Boltzmannstr. 3, 85748 Garching', 'MI 02.07.039', 'U6 Garching Forschungszentrum', 'Di 13-15/nMi/Fr 9-11', '☎️ 089-289-17284/n📩 studienberatung@in.tum.de/nPlease, check the website for current changes and evening appointments', 'http://www.in.tum.de/de/visitenkarten/roden-kinghorst-sibylle/roden-kinghorst-sibylle-sprechstunden/'),
	(53, 'info', 'Studienberatung Informatik (L. Krone)', 'Boltzmannstr. 3, 85748 Garching', 'MI 00.09.037', 'U6 Garching Forschungszentrum', 'Di 15-17/nMi 10-12', 'Mainly for international students/n☎️ 089-289-17867/n📩 krone@in.tum.de/nPlease Check the Website for current changes', 'https://www.in.tum.de/de/visitenkarten/simic-vivija/simic-vivija-sprechstunden/'),
	(54, 'info', 'Rechnerhalle Informatik', 'Boltzmannstr. 3, 85748 Garching', 'MI 00.05.011 & 00.07.023', 'U6 Garching Forschungszentrum', 'Mo-Fr 7-24', 'Internet-Cafe 00.08.057 open 24h❕/nFormulare & Richtlinien: https://bit.ly/2XN0Seu/n☎️  089-289-18018/n📩 rbg@in.tum.de', 'http://www.rbg.tum.de//it-dienste/rechnerpools.html'),
	(55, 'info', 'LRZ Beratung', 'Boltzmannstr. 1, 85748 Garching', 'EG I.E.042', 'U6 Garching Forschungszentrum', 'Mo-Fr 9-17', '☎️ 089-35831-8800/nFAQ: https://bit.ly/2UtZewk/nWhere is it? https://bit.ly/2Tse1et', 'https://www.lrz.de/services/beratung/'),
	(56, 'info', 'LRZ Client-/Server-Betrieb', 'Boltzmannstr. 1, 85748 Garching', 'EG I.E.042', '', '', '', 'https://www.lrz.de/services/client-server/');
```

**Comment by kordianbruck** [comment]
@i-walker here is your API: https://app.tum.de/Api/openingtimes

**Comment by i-walker** [comment]
@kordianbruck Nice!
Let's consider all these issues and my issues working with the legacy code for some API calls:

- [ ]  [#1264, #491 #1225 seem like one basic GET.](https://github.com/TUM-Dev/Campus-Android/issues/1264) We can request them with ?name = "" and ?address = "". Internally, we should use a LIKE (Postgres) operator for address Strings.

- [ ] In addition to the latter. Two nice GET meth. would be a simple Boolean response for an open specified location. with ?time =  t::TIMESTAMP
```kotlin
/** @param loc = User.aroundUser() would be called by the client if no location is specified
*    @param time = now() is also called from client // we may change that I am not sure which is faster right now
/
fun locationIsOpen(loc:Location, time:TIME= now()): Boolean

fun IsOpen(time:Time= now()): Collection<Location>() 
// I don't even care if we  use a HashMap :)
if you're familiar with Higher Kinded Types we can use a Kinds<Container, Location> 
```

- [ ] [Can be messy, but I found an almost easy solution.](https://github.com/TUM-Dev/Campus-Android/issues/678) We Pattern Match over the search string and output max. 3 columns with the highest resemblance. 

- [ ] One PUT/ POST for the Crawler without specifying the Id  

- [ ] One PATCH for Users and the Crawler

- [ ]  Feature Issue: Users can Up/Down Vote the correctness of opening hours so we can debug 

- [ ] Feature Issue: Users can suggest not indexed Locations (only TUM) specifying a name and address // poor Straubing..


I am open for suggestions.

**Comment by i-walker** [comment]
@jacqueline8711 
This is my suggested overview of what the API should cover: 
Disclaimer, I'd like some feedback if I missed something, or is currently not available on the server.

#### On the Server:
- it should have the latest opening hours and rescheduling's
- Crawler should feed the database with changes 

#### locally on the device:
- the user access the info's through the API

#### local DB and offline capabilities 
- As long the app is alive he can access already viewed locations

#### Updating the API and offline DB/ Cache 
// I am pretty open which strategy we choose, but as far as I am concerned @kordianbruck doesn't // want a local DB. Therefore a simple Cache on the device should be sufficient. 

The idea would be to specify for each information resource a crawling strategy.
And then we would specify automated tasks, which invoke the crawler periodically. 
Whenever something breaks we only change the strategy(XPath) or the resource page.

#### missing information & crawling methods
- [ ] Straubing facilities 
- [ ] Weihnstephen lib
- [ ] Barrierefreiheit info's
- [ ] Ansprechparter of other facilities than IT
I think there are more but this is what is I came up with.

**Comment by kordianbruck** [comment]
@i-walker we already have a local DB. The API calls are also cached. Please just add the API as is now. We can refactor it further down the line by creating individual issues for each of your suggestions. I just would like to get the new data loaded from the above API that I've linked as quick as possible in the first step.

Excellent ideas, please open separate issues that further describe those plans. Ideally the User Story in the Android App would describe the benefit for the users.

**Pull request closed without merging**
